### Activity 1
name: Simple Start Up
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build my virtual OS
    runs-on: Ubuntu-latest
    steps:
    - name: checkout my codes
      uses: actions/checkout@v2
    - name: Print and list out content
      run: |
        ls
        echo Hello There!

### Activity 2
    - name: Checkout Private Repo Remotely
      uses: actions/checkout@v2
      with:
        repository: Lowkh/hiddenRepo
        path: file
        token: ${{secrets.TEST_TOKEN}}
    - name: SHow hidden files
      run: |
        cd file
        ls
  
